export const SKILLS = {
  CSS: "/icons/skills/css.svg",
  Docker: "/icons/skills/docker.svg",
  Figma: "/icons/skills/figma.svg",
  Firebase: "/icons/skills/firebase.svg",
  Git: "/icons/skills/git.svg",
  GraphQL: "/icons/skills/graphql.svg",
  HTML: "/icons/skills/html.svg",
  JavaScript: "/icons/skills/javascript.svg",
  Jest: "/icons/skills/jest.svg",
  MongoDB: "/icons/skills/mongodb.svg",
  NextJS: "/icons/skills/nextjs.svg",
  NodeJS: "/icons/skills/nodejs.svg",
  NPM: "/icons/skills/npm.svg",
  Python: "/icons/skills/python.svg",
  React: "/icons/skills/react.svg",
  TailwindCSS: "/icons/skills/tailwindcss.svg",
  TypeScript: "/icons/skills/typescript.svg",
  Vue: "/icons/skills/vue.svg",
} as const;
